name: ${project.name}
main: ${project.groupId}.${project.artifactId}
version: ${project.version}
description: ${project.description}
authors: [Xanthard, OfficialGaming]
softdepend: [VulcanEnchants, VulcanEvents, VulcanStaff, VulcanStats, VulcanTools, VulcanVoting]
